# fly.toml app configuration file for PostOp NextJS frontend
app = 'postop'
primary_region = 'iad'
kill_timeout = '5m0s'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[deploy]
  strategy = 'rolling'

[env]
  # NextJS environment variables
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
